apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: overmods
spec:
  selector:
    matchLabels:
      app: overmods
      service: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: overmods
        service: frontend
    spec:
      containers:
        - image: mykola2312/overmods-frontend:v0.1.1
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8888