apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
  namespace: overmods
spec:
  selector:
    matchLabels:
      app: overmods
      service: frontend
  serviceName: frontend
  template:
    metadata:
      labels:
        app: overmods
        service: frontend
    spec:
      containers:
        - image: mykola2312/overmods-frontend:v0.1.0
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
#          volumeMounts:
#            - mountPath: /var/lib/backend-data
#              name: backend-data
#  volumeClaimTemplates:
#    - metadata:
#        name: backend-data
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        resources:
#          requests:
#            storage: 128Mi
