apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: overmods
spec:
  selector:
    app: overmods
    service: frontend
  type: ClusterIP
  ports:
    - name: frontend
      protocol: TCP
      port: 80