apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: overmods
spec:
  selector:
    app: overmods
    service: backend
  type: NodePort
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31337
