apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: overmods
spec:
  selector:
    app: overmods
    service: frontend
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31337
